name: above_hero_example
description: "Example app to demonstrate the above_hero library"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-97.0.dev

dependencies:
  flutter:
    sdk: flutter

  above_hero:
    path: ../

  universal_back_gesture: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

