name: above_hero
description: "Allows limited control of the Hero widget's z-index by placing page elements ABOVE it"
version: 1.2.0
homepage: https://github.com/TheLastFlame/above_hero
repository: https://github.com/TheLastFlame/above_hero
issue_tracker: https://github.com/TheLastFlame/above_hero/issues
topics:
  - hero
  - z-index
  - overlay
  - navigation
  - animation

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0